# include:
#   - https://gitlab.cgaws.cloud/infra/ci/raw/master/ruby.yml

variables:
  REPOSITORY_URL: 031993550471.dkr.ecr.eu-west-1.amazonaws.com/officer

stages:
  - test
  - build

build:
  stage: build
  image: docker:git
  before_script:
    - apk add go musl-dev
    - go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
    - echo 031993550471.dkr.ecr.eu-west-1.amazonaws.com | /root/go/bin/docker-credential-ecr-login get
  script:
    - docker build --file ./.docker/integration/Dockerfile --tag $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  only:
    - release
    - master