# include:
#   - https://gitlab.cgaws.cloud/infra/ci/raw/master/ruby.yml

variables:
  REPOSITORY_URL: 031993550471.dkr.ecr.eu-west-1.amazonaws.com

stages:
  - test
  - build

build:
  stage: build
  image: docker:git
  before_script:
    - apk add go musl-dev
    - go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
    - mv /root/go/bin/docker-credential-ecr-login /usr/local/bin/docker-credential-ecr-login-alpine
    - "echo > ~/.docker/config.json '{ \"credsStore\": \"ecr-login-alpine\" }'"
  script:
    - docker build --file ./.docker/integration/Dockerfile --tag $REPOSITORY_URL/officer:latest .
    - docker push $REPOSITORY_URL/officer
  only:
    - release
    - master