variables:
  REPOSITORY_URL: 031993550471.dkr.ecr.eu-west-1.amazonaws.com/officer

stages:
  - build

build:
  stage: build
  image: docker:git
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region eu-west-1)
  script:
    - docker pull $REPOSITORY_URL
    - docker build --file ./.docker/integration/Dockerfile --cache-from $REPOSITORY_URL --tag $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  only:
    - release
    - master