# include:
#   - https://gitlab.cgaws.cloud/infra/ci/raw/master/ruby.yml

variables:
  REPOSITORY_URL: 031993550471.dkr.ecr.eu-west-1.amazonaws.com

stages:
  - test
  - build

build:
  stage: build
  image: docker:git
  script:
    - docker build --file ./.docker/integration/Dockerfile --tag $REPOSITORY_URL/officer:latest .
    - docker push $REPOSITORY_URL/officer
  only:
    - release
    - master