variables:
  REPOSITORY_URL: 031993550471.dkr.ecr.eu-west-1.amazonaws.com/officer

stages:
  - build

build:
  stage: build
  image: docker:git
  before_script:
    - which docker-credential-ecr-login
    - cd /usr/local/bin/ && ls -al
    - echo 031993550471.dkr.ecr.eu-west-1.amazonaws.com | docker-credential-ecr-login get
    - echo 031993550471.dkr.ecr.eu-west-1.amazonaws.com | /usr/local/bin/docker-credential-ecr-login get
  script:
    - docker build --file ./.docker/integration/Dockerfile --tag $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  only:
    - release
    - master